// AUTO-GENERATED emoji search names (Unicode character names, lowercased).
// Regenerate with the unicodedata script if EMOJI_CATEGORIES changes.
export const EMOJI_NAMES: Record<string, string> = {
  "\ud83d\ude00": "grinning face",
  "\ud83d\ude03": "smiling face with open mouth",
  "\ud83d\ude04": "smiling face with open mouth and smiling eyes",
  "\ud83d\ude01": "grinning face with smiling eyes",
  "\ud83d\ude06": "smiling face with open mouth and tightly-closed eyes",
  "\ud83d\ude05": "smiling face with open mouth and cold sweat",
  "\ud83d\ude02": "face with tears of joy",
  "\ud83e\udd23": "rolling on the floor laughing",
  "\ud83d\ude42": "slightly smiling face",
  "\ud83d\ude43": "upside-down face",
  "\ud83d\ude09": "winking face",
  "\ud83d\ude0a": "smiling face with smiling eyes",
  "\ud83d\ude07": "smiling face with halo",
  "\ud83e\udd70": "smiling face with smiling eyes and three hearts",
  "\ud83d\ude0d": "smiling face with heart-shaped eyes",
  "\ud83e\udd29": "grinning face with star eyes",
  "\ud83d\ude18": "face throwing a kiss",
  "\ud83d\ude17": "kissing face",
  "\ud83d\ude1a": "kissing face with closed eyes",
  "\ud83d\ude19": "kissing face with smiling eyes",
  "\ud83d\ude0b": "face savouring delicious food",
  "\ud83d\ude1b": "face with stuck-out tongue",
  "\ud83d\ude1c": "face with stuck-out tongue and winking eye",
  "\ud83e\udd2a": "grinning face with one large and one small eye",
  "\ud83d\ude1d": "face with stuck-out tongue and tightly-closed eyes",
  "\ud83e\udd11": "money-mouth face",
  "\ud83e\udd17": "hugging face",
  "\ud83e\udd2d": "smiling face with smiling eyes and hand covering mouth",
  "\ud83e\udd2b": "face with finger covering closed lips",
  "\ud83e\udd14": "thinking face",
  "\ud83e\udd10": "zipper-mouth face",
  "\ud83d\ude10": "neutral face",
  "\ud83d\ude11": "expressionless face",
  "\ud83d\ude36": "face without mouth",
  "\ud83d\ude0f": "smirking face",
  "\ud83d\ude12": "unamused face",
  "\ud83d\ude44": "face with rolling eyes",
  "\ud83d\ude2c": "grimacing face",
  "\ud83d\ude0c": "relieved face",
  "\ud83d\ude14": "pensive face",
  "\ud83d\ude2a": "sleepy face",
  "\ud83e\udd24": "drooling face",
  "\ud83d\ude34": "sleeping face",
  "\ud83d\ude37": "face with medical mask",
  "\ud83e\udd12": "face with thermometer",
  "\ud83e\udd15": "face with head-bandage",
  "\ud83e\udd22": "nauseated face",
  "\ud83e\udd2e": "face with open mouth vomiting",
  "\ud83e\udd75": "overheated face",
  "\ud83e\udd76": "freezing face",
  "\ud83d\ude35": "dizzy face",
  "\ud83e\udd2f": "shocked face with exploding head",
  "\ud83e\udd20": "face with cowboy hat",
  "\ud83e\udd73": "face with party horn and party hat",
  "\ud83d\ude0e": "smiling face with sunglasses",
  "\ud83e\udd13": "nerd face",
  "\ud83e\uddd0": "face with monocle",
  "\ud83d\ude15": "confused face",
  "\ud83d\ude1f": "worried face",
  "\ud83d\ude41": "slightly frowning face",
  "\ud83d\ude2e": "face with open mouth",
  "\ud83d\ude2f": "hushed face",
  "\ud83d\ude32": "astonished face",
  "\ud83d\ude33": "flushed face",
  "\ud83e\udd7a": "face with pleading eyes",
  "\ud83d\ude26": "frowning face with open mouth",
  "\ud83d\ude28": "fearful face",
  "\ud83d\ude30": "face with open mouth and cold sweat",
  "\ud83d\ude25": "disappointed but relieved face",
  "\ud83d\ude22": "crying face",
  "\ud83d\ude2d": "loudly crying face",
  "\ud83d\ude31": "face screaming in fear",
  "\ud83d\ude16": "confounded face",
  "\ud83d\ude23": "persevering face",
  "\ud83d\ude1e": "disappointed face",
  "\ud83d\ude13": "face with cold sweat",
  "\ud83d\ude29": "weary face",
  "\ud83d\ude2b": "tired face",
  "\ud83d\ude24": "face with look of triumph",
  "\ud83d\ude21": "pouting face",
  "\ud83d\ude20": "angry face",
  "\ud83e\udd2c": "serious face with symbols covering mouth",
  "\ud83d\ude08": "smiling face with horns",
  "\ud83d\udc7f": "imp",
  "\ud83d\udc80": "skull",
  "\ud83d\udca9": "pile of poo",
  "\ud83e\udd21": "clown face",
  "\ud83d\udc7b": "ghost",
  "\ud83d\udc7d": "extraterrestrial alien",
  "\ud83e\udd16": "robot face",
  "\ud83d\udc4d": "thumbs up sign",
  "\ud83d\udc4e": "thumbs down sign",
  "\ud83d\udc4c": "ok hand sign",
  "\ud83e\udd0c": "pinched fingers",
  "\ud83e\udd0f": "pinching hand",
  "\u270c\ufe0f": "victory hand",
  "\ud83e\udd1e": "hand with index and middle fingers crossed",
  "\ud83e\udd1f": "i love you hand sign",
  "\ud83e\udd18": "sign of the horns",
  "\ud83e\udd19": "call me hand",
  "\ud83d\udc48": "white left pointing backhand index",
  "\ud83d\udc49": "white right pointing backhand index",
  "\ud83d\udc46": "white up pointing backhand index",
  "\ud83d\udc47": "white down pointing backhand index",
  "\u261d\ufe0f": "white up pointing index",
  "\u270b": "raised hand",
  "\ud83e\udd1a": "raised back of hand",
  "\ud83d\udd90\ufe0f": "raised hand with fingers splayed",
  "\ud83d\udd96": "raised hand with part between middle and ring fingers",
  "\ud83d\udc4b": "waving hand sign",
  "\ud83e\udd1d": "handshake",
  "\ud83d\ude4f": "person with folded hands",
  "\u270d\ufe0f": "writing hand",
  "\ud83d\udc85": "nail polish",
  "\ud83e\udd33": "selfie",
  "\ud83d\udcaa": "flexed biceps",
  "\ud83d\udc4f": "clapping hands sign",
  "\ud83d\ude4c": "person raising both hands in celebration",
  "\ud83d\udc50": "open hands sign",
  "\ud83e\udd32": "palms up together",
  "\ud83d\ude4b": "happy person raising one hand",
  "\ud83e\udd26": "face palm",
  "\ud83e\udd37": "shrug",
  "\ud83d\udc81": "information desk person",
  "\ud83d\ude46": "face with ok gesture",
  "\ud83d\ude45": "face with no good gesture",
  "\ud83e\udde0": "brain",
  "\ud83d\udc40": "eyes",
  "\ud83d\udc41\ufe0f": "eye",
  "\ud83d\udc44": "mouth",
  "\u2764\ufe0f": "heavy black heart",
  "\ud83e\udde1": "orange heart",
  "\ud83d\udc9b": "yellow heart",
  "\ud83d\udc9a": "green heart",
  "\ud83d\udc99": "blue heart",
  "\ud83d\udc9c": "purple heart",
  "\ud83d\udda4": "black heart",
  "\ud83e\udd0d": "white heart",
  "\ud83e\udd0e": "brown heart",
  "\ud83d\udc94": "broken heart",
  "\u2763\ufe0f": "heavy heart exclamation mark ornament",
  "\ud83d\udc95": "two hearts",
  "\ud83d\udc9e": "revolving hearts",
  "\ud83d\udc93": "beating heart",
  "\ud83d\udc97": "growing heart",
  "\ud83d\udc96": "sparkling heart",
  "\ud83d\udc98": "heart with arrow",
  "\ud83d\udc9d": "heart with ribbon",
  "\ud83d\udc9f": "heart decoration",
  "\u2665\ufe0f": "black heart suit",
  "\ud83d\udc8b": "kiss mark",
  "\ud83d\udcaf": "hundred points symbol",
  "\ud83d\udca2": "anger symbol",
  "\ud83d\udca5": "collision symbol",
  "\ud83d\udcab": "dizzy symbol",
  "\ud83d\udca6": "splashing sweat symbol",
  "\ud83d\udca8": "dash symbol",
  "\ud83d\udd73\ufe0f": "hole",
  "\ud83d\udcac": "speech balloon",
  "\ud83d\udcad": "thought balloon",
  "\ud83d\udc36": "dog face",
  "\ud83d\udc31": "cat face",
  "\ud83d\udc2d": "mouse face",
  "\ud83d\udc39": "hamster face",
  "\ud83d\udc30": "rabbit face",
  "\ud83e\udd8a": "fox face",
  "\ud83d\udc3b": "bear face",
  "\ud83d\udc3c": "panda face",
  "\ud83d\udc28": "koala",
  "\ud83d\udc2f": "tiger face",
  "\ud83e\udd81": "lion face",
  "\ud83d\udc2e": "cow face",
  "\ud83d\udc37": "pig face",
  "\ud83d\udc38": "frog face",
  "\ud83d\udc35": "monkey face",
  "\ud83d\ude48": "see-no-evil monkey",
  "\ud83d\ude49": "hear-no-evil monkey",
  "\ud83d\ude4a": "speak-no-evil monkey",
  "\ud83d\udc14": "chicken",
  "\ud83d\udc27": "penguin",
  "\ud83d\udc26": "bird",
  "\ud83d\udc24": "baby chick",
  "\ud83e\udd86": "duck",
  "\ud83e\udd85": "eagle",
  "\ud83e\udd89": "owl",
  "\ud83e\udd87": "bat",
  "\ud83d\udc3a": "wolf face",
  "\ud83d\udc17": "boar",
  "\ud83d\udc34": "horse face",
  "\ud83e\udd84": "unicorn face",
  "\ud83d\udc1d": "honeybee",
  "\ud83d\udc1b": "bug",
  "\ud83e\udd8b": "butterfly",
  "\ud83d\udc0c": "snail",
  "\ud83d\udc1e": "lady beetle",
  "\ud83d\udc1c": "ant",
  "\ud83d\udd77\ufe0f": "spider",
  "\ud83d\udc22": "turtle",
  "\ud83d\udc0d": "snake",
  "\ud83d\udc19": "octopus",
  "\ud83e\udd91": "squid",
  "\ud83e\udd80": "crab",
  "\ud83d\udc20": "tropical fish",
  "\ud83d\udc1f": "fish",
  "\ud83d\udc2c": "dolphin",
  "\ud83d\udc33": "spouting whale",
  "\ud83d\udc0b": "whale",
  "\ud83e\udd88": "shark",
  "\ud83c\udf38": "cherry blossom",
  "\ud83c\udf3b": "sunflower",
  "\ud83c\udf39": "rose",
  "\ud83c\udf37": "tulip",
  "\ud83c\udf32": "evergreen tree",
  "\ud83c\udf35": "cactus",
  "\ud83c\udf40": "four leaf clover",
  "\ud83c\udf41": "maple leaf",
  "\ud83c\udf08": "rainbow",
  "\u2b50": "white medium star",
  "\ud83c\udf19": "crescent moon",
  "\u2600\ufe0f": "black sun with rays",
  "\ud83c\udf4e": "red apple",
  "\ud83c\udf50": "pear",
  "\ud83c\udf4a": "tangerine",
  "\ud83c\udf4b": "lemon",
  "\ud83c\udf4c": "banana",
  "\ud83c\udf49": "watermelon",
  "\ud83c\udf47": "grapes",
  "\ud83c\udf53": "strawberry",
  "\ud83e\uded0": "blueberries",
  "\ud83c\udf52": "cherries",
  "\ud83c\udf51": "peach",
  "\ud83e\udd6d": "mango",
  "\ud83c\udf4d": "pineapple",
  "\ud83e\udd65": "coconut",
  "\ud83e\udd5d": "kiwifruit",
  "\ud83c\udf45": "tomato",
  "\ud83e\udd51": "avocado",
  "\ud83c\udf3d": "ear of maize",
  "\ud83c\udf36\ufe0f": "hot pepper",
  "\ud83e\udd55": "carrot",
  "\ud83c\udf5e": "bread",
  "\ud83e\uddc0": "cheese wedge",
  "\ud83c\udf57": "poultry leg",
  "\ud83c\udf54": "hamburger",
  "\ud83c\udf5f": "french fries",
  "\ud83c\udf55": "slice of pizza",
  "\ud83c\udf2d": "hot dog",
  "\ud83e\udd6a": "sandwich",
  "\ud83c\udf2e": "taco",
  "\ud83c\udf2f": "burrito",
  "\ud83c\udf5c": "steaming bowl",
  "\ud83c\udf5d": "spaghetti",
  "\ud83c\udf63": "sushi",
  "\ud83c\udf71": "bento box",
  "\ud83c\udf5a": "cooked rice",
  "\ud83c\udf69": "doughnut",
  "\ud83c\udf6a": "cookie",
  "\ud83c\udf82": "birthday cake",
  "\ud83c\udf70": "shortcake",
  "\ud83e\uddc1": "cupcake",
  "\ud83c\udf6b": "chocolate bar",
  "\ud83c\udf6c": "candy",
  "\ud83c\udf6d": "lollipop",
  "\ud83c\udf7f": "popcorn",
  "\u2615": "hot beverage",
  "\ud83c\udf75": "teacup without handle",
  "\ud83e\udd64": "cup with straw",
  "\ud83c\udf7a": "beer mug",
  "\ud83c\udf7b": "clinking beer mugs",
  "\ud83c\udf77": "wine glass",
  "\u26bd": "soccer ball",
  "\ud83c\udfc0": "basketball and hoop",
  "\ud83c\udfc8": "american football",
  "\u26be": "baseball",
  "\ud83c\udfbe": "tennis racquet and ball",
  "\ud83c\udfd0": "volleyball",
  "\ud83c\udfc9": "rugby football",
  "\ud83c\udfb1": "billiards",
  "\ud83c\udfd3": "table tennis paddle and ball",
  "\ud83c\udff8": "badminton racquet and shuttlecock",
  "\ud83e\udd45": "goal net",
  "\ud83c\udfd2": "ice hockey stick and puck",
  "\ud83c\udfd1": "field hockey stick and ball",
  "\ud83c\udfcf": "cricket bat and ball",
  "\u26f3": "flag in hole",
  "\ud83c\udfaf": "direct hit",
  "\ud83c\udfb3": "bowling",
  "\ud83c\udfae": "video game",
  "\ud83d\udd79\ufe0f": "joystick",
  "\ud83c\udfb2": "game die",
  "\ud83e\udde9": "jigsaw puzzle piece",
  "\ud83c\udfb0": "slot machine",
  "\ud83c\udfb8": "guitar",
  "\ud83c\udfb9": "musical keyboard",
  "\ud83c\udfba": "trumpet",
  "\ud83c\udfb7": "saxophone",
  "\ud83e\udd41": "drum with drumsticks",
  "\ud83c\udfa7": "headphone",
  "\ud83c\udfa4": "microphone",
  "\ud83c\udfac": "clapper board",
  "\ud83c\udfa8": "artist palette",
  "\ud83c\udfad": "performing arts",
  "\ud83c\udfaa": "circus tent",
  "\ud83c\udf89": "party popper",
  "\ud83c\udf8a": "confetti ball",
  "\ud83c\udf88": "balloon",
  "\ud83c\udf81": "wrapped present",
  "\ud83c\udfc6": "trophy",
  "\ud83e\udd47": "first place medal",
  "\ud83e\udd48": "second place medal",
  "\ud83d\ude97": "automobile",
  "\ud83d\ude95": "taxi",
  "\ud83d\ude99": "recreational vehicle",
  "\ud83d\ude8c": "bus",
  "\ud83c\udfce\ufe0f": "racing car",
  "\ud83d\ude93": "police car",
  "\ud83d\ude91": "ambulance",
  "\ud83d\ude92": "fire engine",
  "\ud83d\ude9a": "delivery truck",
  "\ud83d\ude9c": "tractor",
  "\ud83c\udfcd\ufe0f": "racing motorcycle",
  "\ud83d\udeb2": "bicycle",
  "\ud83d\udef4": "scooter",
  "\ud83d\ude86": "train",
  "\ud83d\ude84": "high-speed train",
  "\ud83d\ude80": "rocket",
  "\ud83d\udef8": "flying saucer",
  "\u2708\ufe0f": "airplane",
  "\ud83d\ude81": "helicopter",
  "\u26f5": "sailboat",
  "\ud83d\udea4": "speedboat",
  "\ud83d\udee5\ufe0f": "motor boat",
  "\ud83c\udfe0": "house building",
  "\ud83c\udfe1": "house with garden",
  "\ud83c\udfe2": "office building",
  "\ud83c\udff0": "european castle",
  "\ud83d\uddfc": "tokyo tower",
  "\ud83d\uddfd": "statue of liberty",
  "\ud83c\udf09": "bridge at night",
  "\ud83c\udfa1": "ferris wheel",
  "\ud83c\udfa2": "roller coaster",
  "\u26f2": "fountain",
  "\ud83c\udfd6\ufe0f": "beach with umbrella",
  "\ud83c\udfdd\ufe0f": "desert island",
  "\ud83c\udfd4\ufe0f": "snow capped mountain",
  "\ud83c\udf0b": "volcano",
  "\ud83d\uddfa\ufe0f": "world map",
  "\ud83e\udded": "compass",
  "\ud83c\udf0d": "earth globe europe-africa",
  "\ud83c\udf0e": "earth globe americas",
  "\ud83d\udcbb": "personal computer",
  "\ud83d\udda5\ufe0f": "desktop computer",
  "\ud83d\udcf1": "mobile phone",
  "\u231a": "watch",
  "\u2328\ufe0f": "keyboard",
  "\ud83d\uddb1\ufe0f": "three button mouse",
  "\ud83d\udda8\ufe0f": "printer",
  "\ud83d\udcbe": "floppy disk",
  "\ud83d\udcbf": "optical disc",
  "\ud83d\udcf7": "camera",
  "\ud83d\udcf8": "camera with flash",
  "\ud83c\udfa5": "movie camera",
  "\ud83d\udcfa": "television",
  "\ud83d\udcfb": "radio",
  "\ud83d\udd0b": "battery",
  "\ud83d\udd0c": "electric plug",
  "\ud83d\udca1": "electric light bulb",
  "\ud83d\udd26": "electric torch",
  "\ud83d\udd6f\ufe0f": "candle",
  "\ud83d\udd11": "key",
  "\ud83d\udd12": "lock",
  "\ud83d\udd13": "open lock",
  "\ud83d\udd27": "wrench",
  "\ud83d\udd28": "hammer",
  "\ud83d\udee0\ufe0f": "hammer and wrench",
  "\u2699\ufe0f": "gear",
  "\ud83e\uddf2": "magnet",
  "\ud83d\udcb0": "money bag",
  "\ud83d\udcb5": "banknote with dollar sign",
  "\ud83d\udcb3": "credit card",
  "\ud83d\udcda": "books",
  "\ud83d\udcd6": "open book",
  "\ud83d\udcdd": "memo",
  "\u270f\ufe0f": "pencil",
  "\ud83d\udd8a\ufe0f": "lower left ballpoint pen",
  "\ud83d\udccc": "pushpin",
  "\ud83d\udcce": "paperclip",
  "\u2702\ufe0f": "black scissors",
  "\ud83d\udd14": "bell",
  "\u2728": "sparkles",
  "\ud83c\udf1f": "glowing star",
  "\ud83d\udd25": "fire",
  "\u2604\ufe0f": "comet",
  "\u26a1": "high voltage sign",
  "\u2757": "heavy exclamation mark symbol",
  "\u2753": "black question mark ornament",
  "\u203c\ufe0f": "double exclamation mark",
  "\u2049\ufe0f": "exclamation question mark",
  "\u2705": "white heavy check mark",
  "\u274c": "cross mark",
  "\u2b55": "heavy large circle",
  "\ud83d\udeab": "no entry sign",
  "\ud83d\udd1e": "no one under eighteen symbol",
  "\u267b\ufe0f": "black universal recycling symbol",
  "\u2714\ufe0f": "heavy check mark",
  "\u2611\ufe0f": "ballot box with check",
  "\ud83d\udd34": "large red circle",
  "\ud83d\udfe0": "large orange circle",
  "\ud83d\udfe1": "large yellow circle",
  "\ud83d\udfe2": "large green circle",
  "\ud83d\udd35": "large blue circle",
  "\ud83d\udfe3": "large purple circle",
  "\u26ab": "medium black circle",
  "\u26aa": "medium white circle",
  "\ud83d\udfe4": "large brown circle",
  "\ud83d\udd36": "large orange diamond",
  "\ud83d\udd37": "large blue diamond",
  "\ud83d\udd3a": "up-pointing red triangle",
  "\ud83d\udd3b": "down-pointing red triangle",
  "\u2660\ufe0f": "black spade suit",
  "\u2666\ufe0f": "black diamond suit",
  "\u2663\ufe0f": "black club suit",
};
