// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptRoomInvite(arg1) {
  return window['go']['main']['App']['AcceptRoomInvite'](arg1);
}

export function AddBuddy(arg1, arg2) {
  return window['go']['main']['App']['AddBuddy'](arg1, arg2);
}

export function ApplyDeviceTransfer(arg1) {
  return window['go']['main']['App']['ApplyDeviceTransfer'](arg1);
}

export function ApproveConnectionRequest(arg1) {
  return window['go']['main']['App']['ApproveConnectionRequest'](arg1);
}

export function AutoSignIn() {
  return window['go']['main']['App']['AutoSignIn']();
}

export function BeginIdentitySetup() {
  return window['go']['main']['App']['BeginIdentitySetup']();
}

export function BeginRecoveryKeyRotation(arg1) {
  return window['go']['main']['App']['BeginRecoveryKeyRotation'](arg1);
}

export function BlockBuddy(arg1) {
  return window['go']['main']['App']['BlockBuddy'](arg1);
}

export function BlockedUsers() {
  return window['go']['main']['App']['BlockedUsers']();
}

export function BuildDeviceTransfer(arg1) {
  return window['go']['main']['App']['BuildDeviceTransfer'](arg1);
}

export function CancelIdentitySetup() {
  return window['go']['main']['App']['CancelIdentitySetup']();
}

export function CancelRecoveryKeyRotation() {
  return window['go']['main']['App']['CancelRecoveryKeyRotation']();
}

export function ChangeEmail(arg1) {
  return window['go']['main']['App']['ChangeEmail'](arg1);
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function ClearConversation(arg1) {
  return window['go']['main']['App']['ClearConversation'](arg1);
}

export function ClearCustomSound(arg1) {
  return window['go']['main']['App']['ClearCustomSound'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CloseConversation(arg1) {
  return window['go']['main']['App']['CloseConversation'](arg1);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function ConfirmIdentitySetup() {
  return window['go']['main']['App']['ConfirmIdentitySetup']();
}

export function ConfirmRecoveryKeyRotation() {
  return window['go']['main']['App']['ConfirmRecoveryKeyRotation']();
}

export function ConversationEncrypted(arg1) {
  return window['go']['main']['App']['ConversationEncrypted'](arg1);
}

export function CreateEncryptedRoom(arg1) {
  return window['go']['main']['App']['CreateEncryptedRoom'](arg1);
}

export function DeclineConnectionRequest(arg1) {
  return window['go']['main']['App']['DeclineConnectionRequest'](arg1);
}

export function DeclineRoomInvite(arg1) {
  return window['go']['main']['App']['DeclineRoomInvite'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function ExportDeviceTransfer(arg1, arg2) {
  return window['go']['main']['App']['ExportDeviceTransfer'](arg1, arg2);
}

export function FindUser(arg1) {
  return window['go']['main']['App']['FindUser'](arg1);
}

export function ForgetRoom(arg1) {
  return window['go']['main']['App']['ForgetRoom'](arg1);
}

export function GetBuddies() {
  return window['go']['main']['App']['GetBuddies']();
}

export function GetBuddyIcon(arg1) {
  return window['go']['main']['App']['GetBuddyIcon'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetCustomSounds() {
  return window['go']['main']['App']['GetCustomSounds']();
}

export function GetIdentityState() {
  return window['go']['main']['App']['GetIdentityState']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetRecoveryKeyStatus() {
  return window['go']['main']['App']['GetRecoveryKeyStatus']();
}

export function GetRoom(arg1) {
  return window['go']['main']['App']['GetRoom'](arg1);
}

export function GetRooms() {
  return window['go']['main']['App']['GetRooms']();
}

export function GetSelf() {
  return window['go']['main']['App']['GetSelf']();
}

export function GetServerSettings() {
  return window['go']['main']['App']['GetServerSettings']();
}

export function Groups() {
  return window['go']['main']['App']['Groups']();
}

export function ImportDeviceTransfer(arg1) {
  return window['go']['main']['App']['ImportDeviceTransfer'](arg1);
}

export function InviteToRoom(arg1, arg2) {
  return window['go']['main']['App']['InviteToRoom'](arg1, arg2);
}

export function JoinRoom(arg1) {
  return window['go']['main']['App']['JoinRoom'](arg1);
}

export function LeaveRoom(arg1) {
  return window['go']['main']['App']['LeaveRoom'](arg1);
}

export function LinkDevice(arg1) {
  return window['go']['main']['App']['LinkDevice'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function LookupProfile(arg1) {
  return window['go']['main']['App']['LookupProfile'](arg1);
}

export function MarkRead(arg1) {
  return window['go']['main']['App']['MarkRead'](arg1);
}

export function MarkVerified(arg1) {
  return window['go']['main']['App']['MarkVerified'](arg1);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function MoveBuddy(arg1, arg2) {
  return window['go']['main']['App']['MoveBuddy'](arg1, arg2);
}

export function PendingConnectionRequests() {
  return window['go']['main']['App']['PendingConnectionRequests']();
}

export function PendingRoomInvites() {
  return window['go']['main']['App']['PendingRoomInvites']();
}

export function PrepareConversation(arg1) {
  return window['go']['main']['App']['PrepareConversation'](arg1);
}

export function ReformRoom(arg1, arg2) {
  return window['go']['main']['App']['ReformRoom'](arg1, arg2);
}

export function RemoveBuddy(arg1) {
  return window['go']['main']['App']['RemoveBuddy'](arg1);
}

export function RemoveDevice(arg1, arg2) {
  return window['go']['main']['App']['RemoveDevice'](arg1, arg2);
}

export function RenameBuddy(arg1, arg2) {
  return window['go']['main']['App']['RenameBuddy'](arg1, arg2);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameGroup'](arg1, arg2);
}

export function ReopenConversation(arg1) {
  return window['go']['main']['App']['ReopenConversation'](arg1);
}

export function RequestUserInfo(arg1) {
  return window['go']['main']['App']['RequestUserInfo'](arg1);
}

export function ResendMessage(arg1, arg2) {
  return window['go']['main']['App']['ResendMessage'](arg1, arg2);
}

export function RoomSecurityInfo(arg1) {
  return window['go']['main']['App']['RoomSecurityInfo'](arg1);
}

export function RotateRoomKey(arg1, arg2) {
  return window['go']['main']['App']['RotateRoomKey'](arg1, arg2);
}

export function SaveRecoveryKeyToFile() {
  return window['go']['main']['App']['SaveRecoveryKeyToFile']();
}

export function SaveServerSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveServerSettings'](arg1, arg2);
}

export function SaveTheme(arg1, arg2) {
  return window['go']['main']['App']['SaveTheme'](arg1, arg2);
}

export function SearchDirectory(arg1, arg2) {
  return window['go']['main']['App']['SearchDirectory'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendRoomMessage(arg1, arg2) {
  return window['go']['main']['App']['SendRoomMessage'](arg1, arg2);
}

export function SetAway(arg1) {
  return window['go']['main']['App']['SetAway'](arg1);
}

export function SetCustomFrame(arg1) {
  return window['go']['main']['App']['SetCustomFrame'](arg1);
}

export function SetCustomSound(arg1, arg2) {
  return window['go']['main']['App']['SetCustomSound'](arg1, arg2);
}

export function SetHistoryEnabled(arg1) {
  return window['go']['main']['App']['SetHistoryEnabled'](arg1);
}

export function SetHistoryRetention(arg1) {
  return window['go']['main']['App']['SetHistoryRetention'](arg1);
}

export function SetProfile(arg1) {
  return window['go']['main']['App']['SetProfile'](arg1);
}

export function SetSkinTone(arg1) {
  return window['go']['main']['App']['SetSkinTone'](arg1);
}

export function SetSoundEnabled(arg1) {
  return window['go']['main']['App']['SetSoundEnabled'](arg1);
}

export function SetSoundMuted(arg1, arg2) {
  return window['go']['main']['App']['SetSoundMuted'](arg1, arg2);
}

export function SetSoundPack(arg1) {
  return window['go']['main']['App']['SetSoundPack'](arg1);
}

export function SetTrayNotify(arg1) {
  return window['go']['main']['App']['SetTrayNotify'](arg1);
}

export function SetTyping(arg1, arg2) {
  return window['go']['main']['App']['SetTyping'](arg1, arg2);
}

export function SignIn(arg1, arg2, arg3) {
  return window['go']['main']['App']['SignIn'](arg1, arg2, arg3);
}

export function SignOff() {
  return window['go']['main']['App']['SignOff']();
}

export function SignedOn() {
  return window['go']['main']['App']['SignedOn']();
}

export function ToggleMaximiseWindow() {
  return window['go']['main']['App']['ToggleMaximiseWindow']();
}

export function TransferTargets() {
  return window['go']['main']['App']['TransferTargets']();
}

export function UnblockBuddy(arg1) {
  return window['go']['main']['App']['UnblockBuddy'](arg1);
}

export function Unverify(arg1) {
  return window['go']['main']['App']['Unverify'](arg1);
}

export function VerificationInfo(arg1) {
  return window['go']['main']['App']['VerificationInfo'](arg1);
}

export function VerifyRecoveryKey(arg1) {
  return window['go']['main']['App']['VerifyRecoveryKey'](arg1);
}

export function WarnUser(arg1, arg2) {
  return window['go']['main']['App']['WarnUser'](arg1, arg2);
}
