// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {state} from '../models';
import {client} from '../models';

export function AcceptRoomInvite(arg1:string):Promise<string>;

export function AddBuddy(arg1:string,arg2:string):Promise<string>;

export function ApproveConnectionRequest(arg1:string):Promise<string>;

export function AutoSignIn():Promise<void>;

export function BeginIdentitySetup():Promise<main.RecoveryKeyInfo>;

export function BeginRecoveryKeyRotation(arg1:string):Promise<main.RecoveryKeyInfo>;

export function BlockBuddy(arg1:string):Promise<string>;

export function BlockedUsers():Promise<Array<string>>;

export function CancelIdentitySetup():Promise<void>;

export function CancelRecoveryKeyRotation():Promise<void>;

export function ChangeEmail(arg1:string):Promise<string>;

export function ChangePassword(arg1:string,arg2:string):Promise<string>;

export function ClearConversation(arg1:string):Promise<void>;

export function ClearCustomSound(arg1:string):Promise<string>;

export function ClearHistory():Promise<string>;

export function CloseConversation(arg1:string):Promise<void>;

export function CloseWindow():Promise<void>;

export function ConfirmIdentitySetup():Promise<string>;

export function ConfirmRecoveryKeyRotation():Promise<string>;

export function ConversationEncrypted(arg1:string):Promise<boolean>;

export function CreateEncryptedRoom(arg1:string):Promise<string>;

export function DeclineConnectionRequest(arg1:string):Promise<string>;

export function DeclineRoomInvite(arg1:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<string>;

export function FindUser(arg1:string):Promise<string>;

export function ForgetRoom(arg1:string):Promise<void>;

export function GetBuddies():Promise<Array<state.Buddy>>;

export function GetBuddyIcon(arg1:string):Promise<string>;

export function GetConversation(arg1:string):Promise<state.Conversation>;

export function GetConversations():Promise<Array<state.Conversation>>;

export function GetCustomSounds():Promise<Record<string, string>>;

export function GetIdentityState():Promise<main.IdentityState>;

export function GetPreferences():Promise<main.Preferences>;

export function GetRecoveryKeyStatus():Promise<main.RecoveryKeyStatus>;

export function GetRoom(arg1:string):Promise<state.Room>;

export function GetRooms():Promise<Array<state.Room>>;

export function GetSelf():Promise<state.Self>;

export function GetServerSettings():Promise<main.ServerSettings>;

export function Groups():Promise<Array<client.GroupInfo>>;

export function InviteToRoom(arg1:string,arg2:string):Promise<string>;

export function JoinRoom(arg1:string):Promise<string>;

export function LeaveRoom(arg1:string):Promise<void>;

export function LinkDevice(arg1:string):Promise<string>;

export function ListDevices():Promise<Array<main.DeviceInfo>>;

export function LookupProfile(arg1:string):Promise<main.ProfilePreview>;

export function MarkRead(arg1:string):Promise<void>;

export function MarkVerified(arg1:string):Promise<string>;

export function MinimizeWindow():Promise<void>;

export function MoveBuddy(arg1:string,arg2:string):Promise<string>;

export function PendingConnectionRequests():Promise<Array<main.ConnectionRequestInfo>>;

export function PendingRoomInvites():Promise<Array<main.RoomInviteInfo>>;

export function PrepareConversation(arg1:string):Promise<boolean>;

export function ReformRoom(arg1:string,arg2:Array<string>):Promise<string>;

export function RemoveBuddy(arg1:string):Promise<string>;

export function RemoveDevice(arg1:string,arg2:string):Promise<string>;

export function RenameBuddy(arg1:string,arg2:string):Promise<string>;

export function RenameGroup(arg1:string,arg2:string):Promise<string>;

export function ReopenConversation(arg1:string):Promise<void>;

export function RequestUserInfo(arg1:string):Promise<void>;

export function RoomSecurityInfo(arg1:string):Promise<main.RoomSecurity>;

export function RotateRoomKey(arg1:string,arg2:Array<string>):Promise<string>;

export function SaveRecoveryKeyToFile():Promise<string>;

export function SaveServerSettings(arg1:string,arg2:number):Promise<string>;

export function SaveTheme(arg1:string,arg2:Record<string, string>):Promise<string>;

export function SearchDirectory(arg1:string,arg2:string):Promise<string>;

export function SendMessage(arg1:string,arg2:string):Promise<string>;

export function SendRoomMessage(arg1:string,arg2:string):Promise<string>;

export function SetAway(arg1:string):Promise<string>;

export function SetCustomFrame(arg1:boolean):Promise<string>;

export function SetCustomSound(arg1:string,arg2:string):Promise<string>;

export function SetHistoryEnabled(arg1:boolean):Promise<string>;

export function SetHistoryRetention(arg1:number):Promise<string>;

export function SetProfile(arg1:string):Promise<string>;

export function SetSkinTone(arg1:number):Promise<string>;

export function SetSoundEnabled(arg1:boolean):Promise<string>;

export function SetSoundMuted(arg1:string,arg2:boolean):Promise<string>;

export function SetSoundPack(arg1:string):Promise<string>;

export function SetTrayNotify(arg1:boolean):Promise<void>;

export function SetTyping(arg1:string,arg2:boolean):Promise<void>;

export function SignIn(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function SignOff():Promise<void>;

export function SignedOn():Promise<boolean>;

export function ToggleMaximiseWindow():Promise<void>;

export function UnblockBuddy(arg1:string):Promise<string>;

export function Unverify(arg1:string):Promise<string>;

export function VerificationInfo(arg1:string):Promise<main.Verification>;

export function VerifyRecoveryKey(arg1:string):Promise<string>;

export function WarnUser(arg1:string,arg2:boolean):Promise<string>;
